### ISSUE TITLE
add to software player

### ISSUE THREAD

**Issue by Avgur123** [yzyhk904/usb-samplerate-unlocker#1]
Hello!

I developed a cloud and streaming player (https://play.google.com/store/apps/details?id=app.beer)

I wanted to know how to "bypass" the native Android sound driver (as far as I heard it reduces sound quality, and bitrate), and send the sound to the usb output in the same unchanged format and with the same bitrate as is in the original file (for example, flac with high resolution)?

As USB Audio Player PRO, Hiby player do.

Can your libraries help me with this task? Maybe you will give any advice?

Thank you!

**Comment by yzyhk904** [comment]
UAPP and the likes cannot transmit audio data unchanged if DRC (in /vendor/etc/audio_policy_configuration.xml) has been enabled on a device like Pixel's, Xperia's, etc. Then you need to replace the XML file to disable DRC. (You can do this by using my root script "USB_SampleRate_Changer" in another repo.)

"USB_SampleRate_Changer" can change the sample rate and the bit depth (usually 96kHz or 48kHz) of the standard USB audio driver dynamically (but not automatically, you need to specify them as you want). If you want to specify a higher sample rate than 96kHz (or 384kHz in the case of using a USB (tunneling) offloading driver), you need "usb_samplerate_unlocker".

Any way, my tools can be used for Hires. audio players using the standard USB audio driver like Apple Music and Amazon Music apps. If you use my tools in your app with root permission, you could change the sample rate and the bit depth of the standard USB driver as you want.

**Comment by Avgur123** [comment]
Hello, thank you for answer.
Unfortunately not all things clear to me)
I have software audio player. It is installed as common player, via downloading from Playstore. 
No root access , no manual install or etc....Can ".so libraries" of "usb_samplerate_unlocker" be integrated in android project to make "clean unchanged" transfer of hi-res audio to USB port?
Or, at least transfer to USB hi res flac with it's normal sample rate (without downsamlping to 44 Hz16 bit )?

**Comment by yzyhk904** [comment]
"usb_samplerate_unlocker" has no ".so libraries" at all.  It modifies "/vendor/lib{64}/libalsautils.so" on the fly virtually with root permission. See README.md in details.

Without root permission, all flac data shall be resampled to 96kHz or 48kHz sample rate in the audioFlinger (the bit depth may be adjusted to capabilities of an attached DAC dynamically). You need a special driver like UAPP.
